"""Initial migration - all tables

Revision ID: e2c25d6e8904
Revises: 
Create Date: 2026-04-15 13:55:28.082498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c25d6e8904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('modelID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('modelFamily', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('modelID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('passwordHash', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('websites',
    sa.Column('websiteID', sa.Integer(), nullable=False),
    sa.Column('rootDomain', sa.String(length=300), nullable=False),
    sa.Column('topLevelDomain', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('websiteID'),
    sa.UniqueConstraint('rootDomain')
    )
    op.create_table('admins',
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.Column('approvalID', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=False),
    sa.Column('privilegeControl', sa.String(length=300), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adminID')
    )
    op.create_table('apiKeys',
    sa.Column('keyID', sa.Integer(), nullable=False),
    sa.Column('keyHash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('lastUsedAt', sa.DateTime(), nullable=True),
    sa.Column('usageCount', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyID'),
    sa.UniqueConstraint('keyHash')
    )
    op.create_table('rateLimitViolations',
    sa.Column('violationID', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('violationID')
    )
    op.create_table('sandboxSessions',
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.Column('isIsolated', sa.Boolean(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('websiteID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['websiteID'], ['websites.websiteID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sessionID')
    )
    op.create_table('actionLogs',
    sa.Column('actionID', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('exportType', sa.String(length=50), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['admins.adminID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actionID')
    )
    op.create_table('grantsPermissions',
    sa.Column('permissionID', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=True),
    sa.Column('action', sa.String(length=300), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['admins.adminID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permissionID')
    )
    op.create_table('manages',
    sa.Column('manageID', sa.Integer(), nullable=False),
    sa.Column('roleID', sa.Integer(), nullable=True),
    sa.Column('roleName', sa.String(length=100), nullable=True),
    sa.Column('roleDescription', sa.String(length=300), nullable=True),
    sa.Column('adminID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminID'], ['admins.adminID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manageID')
    )
    op.create_table('modelVersions',
    sa.Column('versionID', sa.Integer(), nullable=False),
    sa.Column('versionTag', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('creationTimeStamp', sa.DateTime(), nullable=True),
    sa.Column('modelID', sa.Integer(), nullable=False),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['admins.adminID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modelID'], ['models.modelID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('versionID')
    )
    op.create_table('urlSubmissions',
    sa.Column('submissionID', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=3000), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('submissionSource', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('adminID', sa.Integer(), nullable=True),
    sa.Column('websiteID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['admins.adminID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['websiteID'], ['websites.websiteID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('submissionID')
    )
    op.create_table('predictions',
    sa.Column('predictionID', sa.Integer(), nullable=False),
    sa.Column('inferenceTime', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('scoreVector', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('versionID', sa.Integer(), nullable=False),
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessionID'], ['sandboxSessions.sessionID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['versionID'], ['modelVersions.versionID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('predictionID')
    )
    op.create_table('explanations',
    sa.Column('explanationID', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('creationTime', sa.DateTime(), nullable=True),
    sa.Column('predictionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predictionID'], ['predictions.predictionID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('explanationID'),
    sa.UniqueConstraint('predictionID')
    )
    op.create_table('reports',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('generationTime', sa.DateTime(), nullable=True),
    sa.Column('threatLevel', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('predictionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predictionID'], ['predictions.predictionID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reportID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('explanations')
    op.drop_table('predictions')
    op.drop_table('urlSubmissions')
    op.drop_table('modelVersions')
    op.drop_table('manages')
    op.drop_table('grantsPermissions')
    op.drop_table('actionLogs')
    op.drop_table('sandboxSessions')
    op.drop_table('rateLimitViolations')
    op.drop_table('apiKeys')
    op.drop_table('admins')
    op.drop_table('websites')
    op.drop_table('users')
    op.drop_table('models')
    # ### end Alembic commands ###
